
name: build and push Docker Images for multiple platforms


on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    # Generate a timestamp and store it in a variable
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ github.repository }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,liunux/arm64/v8
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}


